events { worker_connections 1024; }

http {
    server {
        listen 80;

        # GUESTS
        location /api/guests {
            proxy_pass http://guests-service:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # ROOMS
        location /api/rooms {
            proxy_pass http://rooms-service:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # RESERVATIONS
        location /api/reservations {
            proxy_pass http://reservations-service:3003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # BILLING
        location /api/billing {
            proxy_pass http://billing-service:3004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # AUTH
        location /api/auth {
            proxy_pass http://auth-service:3005;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # SAAS (PLATAFORMA)
        location /api/saas {
            proxy_pass http://saas-service:3006;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # HOTELES
        location /api/hotels {
            proxy_pass http://hotels-service:3007;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # AUDITORÍA
        location /api/audit {
            proxy_pass http://audit_service:3008;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}